"""add clock_weight_bands table

Revision ID: 252fae609480
Revises: a1b2c3d4e5f6
Create Date: 2026-07-20 14:47:16.151844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '252fae609480'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clock_weight_bands',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('clock', sa.String(length=20), nullable=False),
    sa.Column('regime', sa.String(length=30), nullable=False),
    sa.Column('min_pct', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('max_pct', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('clock_weight_bands')
    # ### end Alembic commands ###
