"""update string size for side in MarketTick model

Revision ID: 311fc754cd36
Revises: c86da9fd8866
Create Date: 2026-04-17 10:42:02.898932

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '311fc754cd36'
down_revision: Union[str, None] = 'c86da9fd8866'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('market_ticks', 'side',
               existing_type=sa.VARCHAR(length=1),
               type_=sa.String(length=50),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('market_ticks', 'side',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=1),
               existing_nullable=True)
    # ### end Alembic commands ###
