"""update orders table

Revision ID: 5be2eef177cd
Revises: 668e9440cab2
Create Date: 2026-05-22 12:15:20.413287

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5be2eef177cd'
down_revision: Union[str, None] = '668e9440cab2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('execution_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('broker_order_id', sa.String(length=100), nullable=True),
    sa.Column('avg_fill_price', sa.Float(), nullable=True),
    sa.Column('filled_qty', sa.Float(), nullable=True),
    sa.Column('commission', sa.Float(), nullable=True),
    sa.Column('error_code', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('raw', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_type', sa.String(length=20), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_events_order_id'), 'order_events', ['order_id'], unique=False)
    op.alter_column('orders', 'side',
               existing_type=postgresql.ENUM('BUY', 'SELL', name='order_side'),
               type_=sa.String(length=10),
               existing_nullable=False)
    op.alter_column('orders', 'order_type',
               existing_type=postgresql.ENUM('MARKET', 'LIMIT', 'STOP', 'STOP_LIMIT', 'OCO', 'TWAP', 'VWAP', 'ICEBERG', name='order_type'),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.alter_column('orders', 'time_in_force',
               existing_type=postgresql.ENUM('GTC', 'IOC', 'FOK', 'DAY', name='time_in_force'),
               type_=sa.String(length=10),
               existing_nullable=False)
    op.alter_column('orders', 'qty',
               existing_type=sa.NUMERIC(precision=20, scale=8),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('orders', 'filled_qty',
               existing_type=sa.NUMERIC(precision=20, scale=8),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('orders', 'price',
               existing_type=sa.NUMERIC(precision=20, scale=8),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('orders', 'stop_price',
               existing_type=sa.NUMERIC(precision=20, scale=8),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('orders', 'avg_fill_price',
               existing_type=sa.NUMERIC(precision=20, scale=8),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('orders', 'status',
               existing_type=postgresql.ENUM('NEW', 'SUBMITTED', 'PARTIAL', 'FILLED', 'CANCELLED', 'REJECTED', 'EXPIRED', name='order_status'),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.alter_column('orders', 'state_history',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False)
    op.alter_column('orders', 'algo_config',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('orders', 'risk_check',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.drop_index('ix_orders_broker_order_id', table_name='orders')
    op.drop_index('ix_orders_status', table_name='orders')
    op.drop_index('ix_orders_strategy_id', table_name='orders')
    op.drop_index('ix_orders_client_order_id', table_name='orders')
    op.create_index(op.f('ix_orders_client_order_id'), 'orders', ['client_order_id'], unique=False)
    op.drop_constraint('orders_user_id_fkey', 'orders', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('orders_user_id_fkey', 'orders', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_orders_client_order_id'), table_name='orders')
    op.create_index('ix_orders_client_order_id', 'orders', ['client_order_id'], unique=True)
    op.create_index('ix_orders_strategy_id', 'orders', ['strategy_id'], unique=False)
    op.create_index('ix_orders_status', 'orders', ['status'], unique=False)
    op.create_index('ix_orders_broker_order_id', 'orders', ['broker_order_id'], unique=False)
    op.alter_column('orders', 'risk_check',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('orders', 'algo_config',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('orders', 'state_history',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('orders', 'status',
               existing_type=sa.String(length=20),
               type_=postgresql.ENUM('NEW', 'SUBMITTED', 'PARTIAL', 'FILLED', 'CANCELLED', 'REJECTED', 'EXPIRED', name='order_status'),
               existing_nullable=False)
    op.alter_column('orders', 'avg_fill_price',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=20, scale=8),
               existing_nullable=True)
    op.alter_column('orders', 'stop_price',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=20, scale=8),
               existing_nullable=True)
    op.alter_column('orders', 'price',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=20, scale=8),
               existing_nullable=True)
    op.alter_column('orders', 'filled_qty',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=20, scale=8),
               existing_nullable=False)
    op.alter_column('orders', 'qty',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=20, scale=8),
               existing_nullable=False)
    op.alter_column('orders', 'time_in_force',
               existing_type=sa.String(length=10),
               type_=postgresql.ENUM('GTC', 'IOC', 'FOK', 'DAY', name='time_in_force'),
               existing_nullable=False)
    op.alter_column('orders', 'order_type',
               existing_type=sa.String(length=20),
               type_=postgresql.ENUM('MARKET', 'LIMIT', 'STOP', 'STOP_LIMIT', 'OCO', 'TWAP', 'VWAP', 'ICEBERG', name='order_type'),
               existing_nullable=False)
    op.alter_column('orders', 'side',
               existing_type=sa.String(length=10),
               type_=postgresql.ENUM('BUY', 'SELL', name='order_side'),
               existing_nullable=False)
    op.drop_index(op.f('ix_order_events_order_id'), table_name='order_events')
    op.drop_table('order_events')
    op.drop_table('execution_results')
    # ### end Alembic commands ###
