"""add unique constrainsts

Revision ID: 668e9440cab2
Revises: c1c6158ed494
Create Date: 2026-05-19 18:29:18.677331

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '668e9440cab2'
down_revision: Union[str, None] = 'c1c6158ed494'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_candles1h_symbol_time', table_name='candles_1h')
    op.create_unique_constraint('uq_candles1h_symbol_time', 'candles_1h', ['symbol_id', 'time'])
    op.drop_index('ix_candles1m_symbol_time', table_name='candles_1m')
    op.create_unique_constraint('uq_candles1m_symbol_time', 'candles_1m', ['symbol_id', 'time'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_candles1m_symbol_time', 'candles_1m', type_='unique')
    op.create_index('ix_candles1m_symbol_time', 'candles_1m', ['symbol_id', 'time'], unique=False)
    op.drop_constraint('uq_candles1h_symbol_time', 'candles_1h', type_='unique')
    op.create_index('ix_candles1h_symbol_time', 'candles_1h', ['symbol_id', 'time'], unique=True)
    # ### end Alembic commands ###
