"""create candle models

Revision ID: c1c6158ed494
Revises: 311fc754cd36
Create Date: 2026-05-19 16:49:07.424142

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c1c6158ed494'
down_revision: Union[str, None] = '311fc754cd36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candles_1h',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('symbol_id', sa.Integer(), nullable=False),
    sa.Column('open', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('high', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('low', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('close', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('volume', sa.Numeric(precision=30, scale=8), nullable=False),
    sa.Column('tick_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['symbol_id'], ['symbols.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_candles1h_symbol_time', 'candles_1h', ['symbol_id', 'time'], unique=True)
    op.create_index('ix_candles1h_time', 'candles_1h', ['time'], unique=False)
    op.create_index(op.f('ix_candles_1h_symbol_id'), 'candles_1h', ['symbol_id'], unique=False)
    op.create_index(op.f('ix_candles_1h_time'), 'candles_1h', ['time'], unique=False)
    op.create_table('candles_1m',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('symbol_id', sa.Integer(), nullable=False),
    sa.Column('open', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('high', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('low', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('close', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('volume', sa.Numeric(precision=30, scale=8), nullable=False),
    sa.Column('tick_count', sa.Integer(), nullable=False),
    sa.Column('has_dq', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['symbol_id'], ['symbols.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_candles1m_symbol_time', 'candles_1m', ['symbol_id', 'time'], unique=False)
    op.create_index('ix_candles1m_time', 'candles_1m', ['time'], unique=False)
    op.create_index(op.f('ix_candles_1m_symbol_id'), 'candles_1m', ['symbol_id'], unique=False)
    op.create_index(op.f('ix_candles_1m_time'), 'candles_1m', ['time'], unique=False)
    op.create_index('ix_dqevents_symbol', 'dq_events', ['symbol_id'], unique=False)
    op.create_index('ix_dqevents_time', 'dq_events', ['time'], unique=False)
    op.add_column('market_ticks', sa.Column('regime', sa.String(length=30), nullable=True))
    op.add_column('market_ticks', sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('market_ticks', sa.Column('candle_ref', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_market_ticks_candle_ref'), 'market_ticks', ['candle_ref'], unique=False)
    op.create_index('ix_markettick_symbol_time', 'market_ticks', ['symbol_id', 'time'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_markettick_symbol_time', table_name='market_ticks')
    op.drop_index(op.f('ix_market_ticks_candle_ref'), table_name='market_ticks')
    op.drop_column('market_ticks', 'candle_ref')
    op.drop_column('market_ticks', 'meta')
    op.drop_column('market_ticks', 'regime')
    op.drop_index('ix_dqevents_time', table_name='dq_events')
    op.drop_index('ix_dqevents_symbol', table_name='dq_events')
    op.drop_index(op.f('ix_candles_1m_time'), table_name='candles_1m')
    op.drop_index(op.f('ix_candles_1m_symbol_id'), table_name='candles_1m')
    op.drop_index('ix_candles1m_time', table_name='candles_1m')
    op.drop_index('ix_candles1m_symbol_time', table_name='candles_1m')
    op.drop_table('candles_1m')
    op.drop_index(op.f('ix_candles_1h_time'), table_name='candles_1h')
    op.drop_index(op.f('ix_candles_1h_symbol_id'), table_name='candles_1h')
    op.drop_index('ix_candles1h_time', table_name='candles_1h')
    op.drop_index('ix_candles1h_symbol_time', table_name='candles_1h')
    op.drop_table('candles_1h')
    # ### end Alembic commands ###
