"""initial tables

Revision ID: c86da9fd8866
Revises: 
Create Date: 2026-04-15 13:49:00.674590

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c86da9fd8866'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('symbols',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=30), nullable=False),
    sa.Column('base_asset', sa.String(length=20), nullable=False),
    sa.Column('quote_asset', sa.String(length=20), nullable=False),
    sa.Column('asset_class', sa.Enum('crypto', 'equities', 'forex', 'futures', 'options', name='asset_class'), nullable=False),
    sa.Column('exchange', sa.String(length=30), nullable=False),
    sa.Column('tick_size', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.Column('lot_size', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.Column('min_qty', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_symbols_symbol'), 'symbols', ['symbol'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('admin', 'trader', 'quant', 'viewer', 'compliance', name='user_role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('mfa_enabled', sa.Boolean(), nullable=False),
    sa.Column('mfa_secret_enc', sa.Text(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_ip', postgresql.INET(), nullable=True),
    sa.Column('failed_logins', sa.SmallInteger(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('actor_email', sa.String(length=255), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('resource_id', sa.String(length=100), nullable=True),
    sa.Column('before_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('request_id', sa.UUID(), nullable=True),
    sa.Column('record_hash', sa.String(length=64), nullable=False),
    sa.Column('prev_hash', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_actor_id'), 'audit_log', ['actor_id'], unique=False)
    op.create_index(op.f('ix_audit_log_event_time'), 'audit_log', ['event_time'], unique=False)
    op.create_table('brokers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('broker_type', sa.Enum('ALPACA', 'BINANCE', 'IBKR', 'CCXT', 'OANDA', 'LMAX', 'CUSTOM', name='broker_type'), nullable=False),
    sa.Column('exchange_id', sa.String(length=50), nullable=True),
    sa.Column('is_paper', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('credentials_enc', sa.Text(), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('CONNECTED', 'DISCONNECTED', 'ERROR', 'PENDING_AUTH', name='broker_status'), nullable=False),
    sa.Column('last_heartbeat', sa.DateTime(timezone=True), nullable=True),
    sa.Column('latency_p99_ms', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_brokers_owner_id'), 'brokers', ['owner_id'], unique=False)
    op.create_table('dq_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('symbol_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('module', sa.Enum('TICK_VALIDATOR', 'DUPLICATE_FILTER', 'TIMESTAMP_CORRECTOR', 'OUTLIER_DETECTOR', 'CONTINUITY_MONITOR', name='dq_module'), nullable=False),
    sa.Column('severity', sa.Enum('INFO', 'WARN', 'ERROR', 'CRITICAL', name='dq_severity'), nullable=False),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['symbol_id'], ['symbols.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dq_events_symbol_id'), 'dq_events', ['symbol_id'], unique=False)
    op.create_index(op.f('ix_dq_events_time'), 'dq_events', ['time'], unique=False)
    op.create_table('kill_switch_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('triggered_by', sa.UUID(), nullable=True),
    sa.Column('trigger_source', sa.String(length=30), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('orders_cancelled', sa.Integer(), nullable=False),
    sa.Column('positions_closed', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['triggered_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('market_ticks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('symbol_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('volume', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('side', sa.String(length=1), nullable=True),
    sa.Column('exchange', sa.String(length=30), nullable=False),
    sa.Column('quality_score', sa.SmallInteger(), nullable=False),
    sa.Column('flags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('dq_result', sa.Enum('PASS', 'FLAG', 'REJECT', name='dq_result'), nullable=False),
    sa.ForeignKeyConstraint(['symbol_id'], ['symbols.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_market_ticks_symbol_id'), 'market_ticks', ['symbol_id'], unique=False)
    op.create_index(op.f('ix_market_ticks_time'), 'market_ticks', ['time'], unique=False)
    op.create_table('regime_states',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('symbol_id', sa.Integer(), nullable=False),
    sa.Column('regime_label', sa.String(length=30), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('hmm_probs', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('detected_by', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['symbol_id'], ['symbols.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_regime_states_symbol_id'), 'regime_states', ['symbol_id'], unique=False)
    op.create_index(op.f('ix_regime_states_time'), 'regime_states', ['time'], unique=False)
    op.create_table('risk_limits',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('scope', sa.Enum('global', 'per_strategy', 'per_symbol', 'per_user', name='limit_scope'), nullable=False),
    sa.Column('scope_id', sa.String(length=50), nullable=True),
    sa.Column('limit_type', sa.String(length=50), nullable=False),
    sa.Column('limit_value', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('current_value', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('breach_action', sa.Enum('ALERT', 'BLOCK', 'KILL_SWITCH', name='breach_action'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('strategies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('generation', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('lifecycle_stage', sa.Enum('IDEA', 'RESEARCH', 'BACKTEST', 'PAPER', 'LIVE_SMALL', 'SCALED', 'MONITOR', 'RETIRED', name='lifecycle_stage'), nullable=False),
    sa.Column('hypothesis', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('feature_list', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('allowed_symbols', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('allowed_regimes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('risk_profile', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('code_hash', sa.String(length=64), nullable=True),
    sa.Column('training_data_hash', sa.String(length=64), nullable=True),
    sa.Column('fitness_score', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('sharpe_last', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('gate_history', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('mutation_log', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('audit_hash', sa.String(length=64), nullable=True),
    sa.Column('is_paper_only', sa.Boolean(), nullable=False),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('deployed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retired_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retirement_reason', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['strategies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_strategies_created_by'), 'strategies', ['created_by'], unique=False)
    op.create_index(op.f('ix_strategies_lifecycle_stage'), 'strategies', ['lifecycle_stage'], unique=False)
    op.create_table('user_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('refresh_token_hash', sa.String(length=64), nullable=False),
    sa.Column('device_info', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('refresh_token_hash')
    )
    op.create_index(op.f('ix_user_sessions_user_id'), 'user_sessions', ['user_id'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('severity', sa.Enum('P1', 'P2', 'P3', 'P4', name='alert_severity'), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('strategy_id', sa.UUID(), nullable=True),
    sa.Column('symbol_id', sa.Integer(), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_acknowledged', sa.Boolean(), nullable=False),
    sa.Column('acknowledged_by', sa.UUID(), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ack_note', sa.Text(), nullable=True),
    sa.Column('auto_resolved', sa.Boolean(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['acknowledged_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ),
    sa.ForeignKeyConstraint(['symbol_id'], ['symbols.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_created_at'), 'alerts', ['created_at'], unique=False)
    op.create_index(op.f('ix_alerts_is_acknowledged'), 'alerts', ['is_acknowledged'], unique=False)
    op.create_index(op.f('ix_alerts_severity'), 'alerts', ['severity'], unique=False)
    op.create_table('backtest_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('strategy_id', sa.UUID(), nullable=False),
    sa.Column('submitted_by', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'RUNNING', 'COMPLETE', 'FAILED', name='backtest_status'), nullable=False),
    sa.Column('progress_pct', sa.Integer(), nullable=False),
    sa.Column('celery_task_id', sa.String(length=100), nullable=True),
    sa.Column('start_date', sa.String(length=10), nullable=False),
    sa.Column('end_date', sa.String(length=10), nullable=False),
    sa.Column('symbols', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('cost_model', sa.Enum('FULL', 'ZERO_COST', 'FEES_ONLY', 'SLIPPAGE_ONLY', name='cost_model'), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('sharpe_ratio', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('max_drawdown', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('total_return', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('trade_count', sa.Integer(), nullable=True),
    sa.Column('win_rate', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('profit_factor', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('full_report', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('equity_curve', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ),
    sa.ForeignKeyConstraint(['submitted_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_backtest_jobs_status'), 'backtest_jobs', ['status'], unique=False)
    op.create_index(op.f('ix_backtest_jobs_strategy_id'), 'backtest_jobs', ['strategy_id'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_order_id', sa.String(length=100), nullable=True),
    sa.Column('broker_order_id', sa.String(length=100), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('broker_id', sa.UUID(), nullable=False),
    sa.Column('strategy_id', sa.UUID(), nullable=True),
    sa.Column('symbol_id', sa.Integer(), nullable=False),
    sa.Column('side', sa.Enum('BUY', 'SELL', name='order_side'), nullable=False),
    sa.Column('order_type', sa.Enum('MARKET', 'LIMIT', 'STOP', 'STOP_LIMIT', 'OCO', 'TWAP', 'VWAP', 'ICEBERG', name='order_type'), nullable=False),
    sa.Column('time_in_force', sa.Enum('GTC', 'IOC', 'FOK', 'DAY', name='time_in_force'), nullable=False),
    sa.Column('qty', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('filled_qty', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('price', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('stop_price', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('avg_fill_price', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('status', sa.Enum('NEW', 'SUBMITTED', 'PARTIAL', 'FILLED', 'CANCELLED', 'REJECTED', 'EXPIRED', name='order_status'), nullable=False),
    sa.Column('state_history', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('algo_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('reject_reason', sa.Text(), nullable=True),
    sa.Column('risk_check', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('filled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['broker_id'], ['brokers.id'], ),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ),
    sa.ForeignKeyConstraint(['symbol_id'], ['symbols.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_broker_id'), 'orders', ['broker_id'], unique=False)
    op.create_index(op.f('ix_orders_broker_order_id'), 'orders', ['broker_order_id'], unique=False)
    op.create_index(op.f('ix_orders_client_order_id'), 'orders', ['client_order_id'], unique=True)
    op.create_index(op.f('ix_orders_status'), 'orders', ['status'], unique=False)
    op.create_index(op.f('ix_orders_strategy_id'), 'orders', ['strategy_id'], unique=False)
    op.create_index(op.f('ix_orders_symbol_id'), 'orders', ['symbol_id'], unique=False)
    op.create_index(op.f('ix_orders_user_id'), 'orders', ['user_id'], unique=False)
    op.create_table('pnl_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('strategy_id', sa.UUID(), nullable=True),
    sa.Column('total_equity', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('realized_pnl', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('unrealized_pnl', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('cash_balance', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('drawdown_pct', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('snapshot_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pnl_snapshots_snapshot_at'), 'pnl_snapshots', ['snapshot_at'], unique=False)
    op.create_index(op.f('ix_pnl_snapshots_user_id'), 'pnl_snapshots', ['user_id'], unique=False)
    op.create_table('positions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('broker_id', sa.UUID(), nullable=False),
    sa.Column('strategy_id', sa.UUID(), nullable=True),
    sa.Column('symbol_id', sa.Integer(), nullable=False),
    sa.Column('side', sa.Enum('LONG', 'SHORT', name='position_side'), nullable=False),
    sa.Column('qty', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('avg_cost', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('realized_pnl', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('unrealized_pnl', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('margin_used', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('is_open', sa.Boolean(), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['broker_id'], ['brokers.id'], ),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ),
    sa.ForeignKeyConstraint(['symbol_id'], ['symbols.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_positions_is_open'), 'positions', ['is_open'], unique=False)
    op.create_index(op.f('ix_positions_symbol_id'), 'positions', ['symbol_id'], unique=False)
    op.create_index(op.f('ix_positions_user_id'), 'positions', ['user_id'], unique=False)
    op.create_table('fills',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('broker_fill_id', sa.String(length=100), nullable=True),
    sa.Column('symbol_id', sa.Integer(), nullable=False),
    sa.Column('side', sa.Enum('BUY', 'SELL', name='order_side'), nullable=False),
    sa.Column('qty', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('price', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('commission', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('slippage_bps', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('spread_cost_bps', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('funding_cost', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('total_cost', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('filled_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['symbol_id'], ['symbols.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fills_order_id'), 'fills', ['order_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fills_order_id'), table_name='fills')
    op.drop_table('fills')
    op.drop_index(op.f('ix_positions_user_id'), table_name='positions')
    op.drop_index(op.f('ix_positions_symbol_id'), table_name='positions')
    op.drop_index(op.f('ix_positions_is_open'), table_name='positions')
    op.drop_table('positions')
    op.drop_index(op.f('ix_pnl_snapshots_user_id'), table_name='pnl_snapshots')
    op.drop_index(op.f('ix_pnl_snapshots_snapshot_at'), table_name='pnl_snapshots')
    op.drop_table('pnl_snapshots')
    op.drop_index(op.f('ix_orders_user_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_symbol_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_strategy_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_status'), table_name='orders')
    op.drop_index(op.f('ix_orders_client_order_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_broker_order_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_broker_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_backtest_jobs_strategy_id'), table_name='backtest_jobs')
    op.drop_index(op.f('ix_backtest_jobs_status'), table_name='backtest_jobs')
    op.drop_table('backtest_jobs')
    op.drop_index(op.f('ix_alerts_severity'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_is_acknowledged'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_created_at'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_user_sessions_user_id'), table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_index(op.f('ix_strategies_lifecycle_stage'), table_name='strategies')
    op.drop_index(op.f('ix_strategies_created_by'), table_name='strategies')
    op.drop_table('strategies')
    op.drop_table('risk_limits')
    op.drop_index(op.f('ix_regime_states_time'), table_name='regime_states')
    op.drop_index(op.f('ix_regime_states_symbol_id'), table_name='regime_states')
    op.drop_table('regime_states')
    op.drop_index(op.f('ix_market_ticks_time'), table_name='market_ticks')
    op.drop_index(op.f('ix_market_ticks_symbol_id'), table_name='market_ticks')
    op.drop_table('market_ticks')
    op.drop_table('kill_switch_events')
    op.drop_index(op.f('ix_dq_events_time'), table_name='dq_events')
    op.drop_index(op.f('ix_dq_events_symbol_id'), table_name='dq_events')
    op.drop_table('dq_events')
    op.drop_index(op.f('ix_brokers_owner_id'), table_name='brokers')
    op.drop_table('brokers')
    op.drop_index(op.f('ix_audit_log_event_time'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_actor_id'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_symbols_symbol'), table_name='symbols')
    op.drop_table('symbols')
    # ### end Alembic commands ###
