"""add quant_decisions table

Revision ID: df1630e38492
Revises: 252fae609480
Create Date: 2026-07-20 16:05:37.250885

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df1630e38492'
down_revision: Union[str, None] = '252fae609480'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quant_decisions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('symbol_id', sa.Integer(), nullable=False),
    sa.Column('decision', sa.String(length=10), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('regime_label', sa.String(length=30), nullable=False),
    sa.Column('price_at_decision', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('horizon_minutes', sa.Integer(), nullable=False),
    sa.Column('graded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('outcome', sa.String(length=10), nullable=True),
    sa.Column('price_at_grading', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['symbol_id'], ['symbols.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quant_decisions_symbol_id'), 'quant_decisions', ['symbol_id'], unique=False)
    op.create_index(op.f('ix_quant_decisions_time'), 'quant_decisions', ['time'], unique=False)
    op.create_index('ix_quantdecision_symbol_graded', 'quant_decisions', ['symbol_id', 'graded_at'], unique=False)
    # ### end Alembic commands ###
    # NOTE: autogenerate also proposed dropping 'ix_orders_user_client_order_id_unique'
    # on 'orders' -- that's pre-existing drift unrelated to this migration
    # (this table's own change), stripped out to keep this migration scoped
    # to quant_decisions only.


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_quantdecision_symbol_graded', table_name='quant_decisions')
    op.drop_index(op.f('ix_quant_decisions_time'), table_name='quant_decisions')
    op.drop_index(op.f('ix_quant_decisions_symbol_id'), table_name='quant_decisions')
    op.drop_table('quant_decisions')
    # ### end Alembic commands ###
